###creer coloc en post
POST http://localhost:5000/colocs/create
Content-Type: application/json

{
    
    "name": "Test",
    "user_id": 1
}

###recuperer une coloc
GET http://localhost:5000/colocs/9
Content-Type: application/json

###mettre a jour coloc
PATCH http://localhost:5000/colocs/9
Content-Type: application/json

{
    "name":"Marche"
}

###supprimer une coloc
DELETE http://localhost:5000/colocs/9
Content-Type: application/json

###rejoindre une coloc en post
POST http://localhost:5000/colocs/join
Content-Type: application/json

{
    "groupe_code_valid":"72279838"
}