###creer route en post
POST http://localhost:5000/colocs
Content-Type: application/json

{
    "name": "Les Fous"
}

###recuperer une coloc
GET http://localhost:5000/colocs/2
Content-Type: application/json


