###creer coloc en post
POST http://172.25.192.189:5000/user/3/colocs/create
Cookie:connect.sid=s%3A6NchkhTx-yB_tlSZM_wZet_v4Xtm6fuC.1W5KPMcocmGNHeVNSAuJXMq4UPwC2IluazKEmztERJ4; Path=/; HttpOnly
Content-Type: application/json

{
    
    "name": "test cookie"
}

###recuperer une coloc
GET http://172.25.192.189:5000/user/5/colocs/2
Cookie: connect.sid=s%3A6NchkhTx-yB_tlSZM_wZet_v4Xtm6fuC.1W5KPMcocmGNHeVNSAuJXMq4UPwC2IluazKEmztERJ4; Path=/; HttpOnly
Content-Type: application/json

###mettre a jour coloc
PATCH http://172.25.192.189:5000/colocs/5
Content-Type: application/json

{
    "name":"Marche"
}

###supprimer une coloc
DELETE http://localhost:5000/colocs/9
Content-Type: application/json

###rejoindre une coloc en post
POST http://172.25.192.189:5000/user/5/colocs/join
Cookie:connect.sid=s%3A6NchkhTx-yB_tlSZM_wZet_v4Xtm6fuC.1W5KPMcocmGNHeVNSAuJXMq4UPwC2IluazKEmztERJ4; Path=/; HttpOnly
Content-Type: application/json

{
    "groupe_code_valid":"23049609"
}

###quitter une coloc en post
POST http://172.25.192.189:5000/colocs/5/leave
Cookie:connect.sid=s%3A6NchkhTx-yB_tlSZM_wZet_v4Xtm6fuC.1W5KPMcocmGNHeVNSAuJXMq4UPwC2IluazKEmztERJ4; Path=/; HttpOnly
Content-Type: application/json
