###creer route SIGNUP en post
POST http://localhost:5000/signup
Content-Type: application/json

{
    "firstname":"Mickey",
    "email":"mickey.4870@gmail.com",
    "password":"Mickey44000!",
    "color": "#343434"
    
}

###creer route LOGIN en post
POST http://172.25.192.189:5000/login
Content-Type: application/json

{
    "email":"nono@gmail.com",
    "password":"Nonoellie321"  
}

###creer route UPDATE en put/update

PUT http://172.25.192.189:5000/user/6/profile
Content-Type: application/json

{
    "firstname": "NoellieTheBest",
    "email": "",
    "color": "#TR0158",
    "password": ""
}

###creer route DELETE en delete
DELETE http://172.25.192.189:5000/user/5/delete
Cookie: connect.sid=s%3AtSL0v_3J-Ibu5uzqhhF8x3uEbDQZDQR-.u7rhilKQmFxy6AcUeUYlo%2FUb97FoPNuL%2FGJayn9YcS8; Path=/; HttpOnly
Content-Type: application/json

###creer route GET consultation Profil par le user
DELETE http://172.25.192.189:5000/user/5/profile
Cookie: connect.sid=s%3AtSL0v_3J-Ibu5uzqhhF8x3uEbDQZDQR-.u7rhilKQmFxy6AcUeUYlo%2FUb97FoPNuL%2FGJayn9YcS8; Path=/; HttpOnly
Content-Type: application/json

