###Créer une nouvelle tâche
POST http://localhost:5000/tasks
Cookie: connect.sid=s%3ArQ00a7aPKIRhWg5o7xDQzxaDJxdDJ_VB.cLij2ikPFdTEK3iDd%2BwEdy0XZkLoOtTPrsx9S5isOAg; Path=/; Expires=Fri, 12 Apr 2024 12:13:59 GMT; HttpOnly
Content-Type: application/json

{
    "description": "Faire les courses",
    "is_predefined": false,
    "is_done": false,
    "frequency": 14
}

### Get All Tasks
GET http://localhost:5000/tasks
Content-Type: application/json


### Update Task
PUT http://localhost:5000/tasks/3
Cookie: connect.sid=s%3ASUeTCoxS7n3-ahldlmXHGTDbYjwogl-B.dK5YHuWM3P8KZU%2FaABP%2Bb6IcSjVhWKWGZqsmXT56x5s; Path=/; Expires=Fri, 12 Apr 2024 12:33:47 GMT; HttpOnly
Content-Type: application/json

{
    "description": "Aspiro",
    "is_predefined": false,
    "is_done": true,
    "frequency": 7
}


### Delete Task
DELETE http://localhost:5000/tasks/4
Cookie: connect.sid=s%3AENBmV_GtRN_u1wkI5dBQ4wAUEyi2__fJ.YX3%2Fqq%2F3nLLPxD7eIalziZ1AOw558BeaEzltxx62M9Q; Path=/; Expires=Fri, 12 Apr 2024 12:43:25 GMT; HttpOnly
Content-Type: application/json


# ------------ RESET PASSWORD -------------------

### Demande de réinitialisation du mot de passe
POST http://172.25.192.189:5000/request-reset
Content-Type: application/json

{
    "email": "mickael.4870@gmail.com"
}

### Valider le token de réinitialisation du mot de passe
### Remplace :token par le token réel reçu par email
GET http://172.25.192.189:5000/validate-reset-token/ad4184959f0ad698d260b5e077948a1f0507046b

###

### Réinitialiser le mot de passe
### Assure-toi de remplacer :userId par l'identifiant de l'utilisateur
### et :token par le token réel
POST http://172.25.192.189:5000/reset-password
Content-Type: application/json

{
    "userId": 7,
    "token": "ad4184959f0ad698d260b5e077948a1f0507046b",
    "newPassword": "nouveauMotDePasse"
}

### Démarrer l'Authentification avec Google
GET http://172.25.192.189:5000/auth/google
