###creer route SIGNUP en post
POST http://localhost:5000/signup
Content-Type: application/json


{
    "firstname":"John Doe",
    "email":"johndoe@index.com",
    "password":"DoeJohn4444!",
    "color": "#343434"
    
}

###creer route LOGIN en post
POST http://localhost:5000/login
Content-Type: application/json


{
    "email":"balou@index.com",
    "password":"Balou4444!"  
}

###creer route UPDATE en put/update

PUT http://localhost:5000/profile
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3MCwiaWF0IjoxNzEzMjk1Nzc2LCJleHAiOjE3MTM5MDA1NzZ9.TL517GSbu5-VPWvUMCeMxua3rpWmpkd_G9rJcwGbMPo

{
    "firstname": "John Doe 44",
    "email": "",
    "color": "",
    "password": ""
}

###creer route DELETE en delete
DELETE http://localhost:5000/delete
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2NywiaWF0IjoxNzEzMjkxOTMwLCJleHAiOjE3MTM4OTY3MzB9.7jaHJ7XUoCL3SXWGLdHHJt4LSyh9ABIo956PkfFVH88

###creer route GET consultation Profil par le user
GET http://localhost:5000/profile
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2NywiaWF0IjoxNzEzMjkxOTMwLCJleHAiOjE3MTM4OTY3MzB9.7jaHJ7XUoCL3SXWGLdHHJt4LSyh9ABIo956PkfFVH88

###Route pour recuperer tous les users d'une coloc
GET http://localhost:5000/colocs/10/users
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJpYXQiOjE3MTMyNTUyNjgsImV4cCI6MTcxMzI1ODg2OH0.5gWQbOOIcIEM6ry1m24UxM0BfwMs576YyuW0ag3RGR8

###Route pour recuperer tous les tasks d'une coloc
GET http://localhost:5000/colocs/10/tasks
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJpYXQiOjE3MTMyNTg5MTcsImV4cCI6MTcxMzI2MjUxN30.FarMaknLtLlJxsz8X1NYUrgN0w5NhOdjgUdTYsHiNxQ


### route pour deconnexion user

POST http://localhost:5000/user/4/logout
Authorization : token xxx

###route pour un refresh token
GET http://localhost:5000/refresh-token