###creer route SIGNUP en post
POST http://172.25.192.189:5000/signup
Content-Type: application/json


{
    "firstname":"test",
    "email":"test.4870@gmail.com",
    "password":"Test44000!",
    "color": "#343434"
    
}

###creer route LOGIN en post
POST http://172.25.192.189:5000/login
Content-Type: application/json


{
    "email":"test.4870@gmail.com",
    "password":"Test44000!"  
}

###creer route UPDATE en put/update

PUT http://172.25.192.189:5000/user/10/profile
Content-Type: application/json
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiaWF0IjoxNzEzMTkxMDAzLCJleHAiOjE3MTMxOTQ2MDN9.g-k_WnSKkuY0iaHHxeEXmw1zHRct9uoQ4rMwXCKt5_o

{
    "firstname": "TestUpDate",
    "email": "",
    "color": "",
    "password": ""
}

###creer route DELETE en delete
DELETE http://172.25.192.189:5000/user/5/delete
Authorization : token xxx

###creer route GET consultation Profil par le user
GET http://172.25.192.189:5000/profile
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiaWF0IjoxNzEzMTkyMDI3LCJleHAiOjE3MTMxOTU2Mjd9.mmVudHM9TI6BE-cTimpVBD8pw_Dfx4geuhkBcGE23XA

###Route pour recuperer tous les users d'une coloc
GET http://localhost:5000/colocs/10/users
Authorization : token xxx

###Route pour recuperer tous les tasks d'une coloc
GET http://localhost:5000/colocs/10/tasks
Authorization : token xxx


### route pour deconnexion user

POST http://localhost:5000/user/4/logout
Authorization : token xxx