###creer coloc en post
POST http://localhost:3000/colocs/create
Cookie: connect.sid=s%3AzVqAFsODVCFnie5vdT-UXCzRLaSEMRaS.HO1%2BSU3B5%2BOTEbz1N6qdk44VKRqq18BvOq8qD9K7ALQ; Path=/; Expires=Thu, 11 Apr 2024 11:55:47 GMT; HttpOnly
Content-Type: application/json

{
    
    "name": "La colocation"
}

###recuperer une coloc
GET http://localhost:5000/colocs/10
Cookie: connect.sid=s%3APxrnzcxQxyWs3ONdpQoPnCpKtQB7MvnC.oUQfxTHsWMyEqJjjgHNTODIHZ35eRugRgiNQLSnfXbc; Path=/; Expires=Fri, 12 Apr 2024 09:12:36 GMT; HttpOnly
Content-Type: application/json

###mettre a jour coloc
PATCH http://172.25.192.189:5000/colocs/5
Content-Type: application/json

{
    "name":"Marche"
}

###supprimer une coloc
DELETE http://localhost:5000/colocs/9
Content-Type: application/json

###rejoindre une coloc en post
POST http://localhost:5000/colocs/join
Cookie:connect.sid=s%3Aixt27oc-vSzgmQuBmcC0JY7IR0NcqbxL.IkllbIPHk%2FzBhdgmLO0qyfA4Vs5yoA85oUX%2FF3ZMxV8; Path=/; Expires=Fri, 12 Apr 2024 11:38:04 GMT; HttpOnly
Content-Type: application/json

{
    "groupe_code_valid":"74275992"
}

###quitter une coloc en post
POST http://localhost:5000/colocs/10/leave
Cookie:connect.sid=s%3ASw7xucIT0gNNLBMjBpeeq08rQAm4PLcP.LLLHLz%2FB436%2BDH4YjJQgcmcRak1rFmRpD4FlV5Xm%2BQ4; Path=/; Expires=Fri, 12 Apr 2024 09:18:30 GMT; HttpOnly
Content-Type: application/json
