###creer route SIGNUP en post
POST http://localhost:5000/signup
Content-Type: application/json


{
    "firstname":"EMMANUELLE",
    "email":"EMMANUELLE@index.com",
    "password":"Emmanuelle444!",
    "color": "#343434"
    
}

###creer route LOGIN en post
POST http://localhost:5000/login
Content-Type: application/json


{
    "email":"EMMANUELLE@index.com",
    "password":"Emmanuelle444!"  
}

###creer route UPDATE en put/update

PUT http://localhost:5000/profile
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3NywiaWF0IjoxNzEzNTE4MzkyLCJleHAiOjE3MTM1MTg0NTJ9.j7LTMwkeg5Onpd69zRAEXySe_WxDsgP7Bx6N_FX46_o

{
    "firstname": "EMMANUELLE 88",
    "email": "",
    "color": "",
    "password": ""
}

###creer route DELETE en delete
DELETE http://localhost:5000/delete
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3NiwiaWF0IjoxNzEzNDI5MjA4LCJleHAiOjE3MTM0MzI4MDh9.8YkK_nQfoCTVgCC6b8PPuD1k5k6EFYu2aNnwO-EXDM4

###creer route GET consultation Profil par le user
GET http://localhost:5000/profile
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3NywiaWF0IjoxNzEzNTE4MzU4LCJleHAiOjE3MTM1MTg0MTh9.tMDy165jhBJcIYgJN_gtIetQgLRshpqSDc5V1uA9lnk

###Route pour recuperer tous les users d'une coloc
GET http://localhost:5000/colocs/10/users
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJpYXQiOjE3MTMyNTUyNjgsImV4cCI6MTcxMzI1ODg2OH0.5gWQbOOIcIEM6ry1m24UxM0BfwMs576YyuW0ag3RGR8

###Route pour recuperer tous les tasks d'une coloc
GET http://localhost:5000/colocs/10/tasks
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyNCwiaWF0IjoxNzEzNTMxMTQ2LCJleHAiOjE3MTM1MzEyMDZ9.Uhv6ObS7oZJ5f9lN9PLvR7xYQrJMDdIPlNpOei-eDHE


### route pour deconnexion user

POST http://localhost:5000/logout
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3NywiaWF0IjoxNzEzNTE4MjI5LCJleHAiOjE3MTM1MTgyODl9.1skS7yiCki1ObAeG7vlDAtE-gm5h69jFFxZ0q8T5LII


### route pour générer un refresh token
POST http://localhost:5000/refresh-Token
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyNCwiaWF0IjoxNzEzNTMxMjM0LCJleHAiOjE3MTM1MzEyOTR9.a2psK8S3FFWq9G26XRbG1t-Rl6FPLvZsap08O2QYHNU
