###creer coloc en post
POST http://localhost:5000/colocs/create
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2OSwiaWF0IjoxNzEzMjk2MzYxLCJleHAiOjE3MTM5MDExNjF9._t_Htnv3dCzzL5FNmyoeQdJ8_uA0keusWuZoTMVru14
Content-Type: application/json

{
    
    "name": "refresh"
}

###recuperer une coloc
GET http://localhost:5000/colocs/3
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2OSwiaWF0IjoxNzEzMjk2MzYxLCJleHAiOjE3MTM5MDExNjF9._t_Htnv3dCzzL5FNmyoeQdJ8_uA0keusWuZoTMVru14
Content-Type: application/json

###mettre a jour coloc
PATCH http://localhost:5000/colocs/3
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2OSwiaWF0IjoxNzEzMjk2MzYxLCJleHAiOjE3MTM5MDExNjF9._t_Htnv3dCzzL5FNmyoeQdJ8_uA0keusWuZoTMVru14
Content-Type: application/json

{
    "name":"Refresh1"
}

###supprimer une coloc
DELETE http://localhost:5000/colocs/10
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJpYXQiOjE3MTMyNTUyNjgsImV4cCI6MTcxMzI1ODg2OH0.5gWQbOOIcIEM6ry1m24UxM0BfwMs576YyuW0ag3RGR8

###rejoindre une coloc en post
POST http://localhost:5000/colocs/join
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJpYXQiOjE3MTMyNTUyNjgsImV4cCI6MTcxMzI1ODg2OH0.5gWQbOOIcIEM6ry1m24UxM0BfwMs576YyuW0ag3RGR8
Content-Type: application/json

{
    "groupe_code_valid":"74275992"
}

###quitter une coloc en post
POST http://localhost:5000/colocs/10/leave
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJpYXQiOjE3MTMyNTUyNjgsImV4cCI6MTcxMzI1ODg2OH0.5gWQbOOIcIEM6ry1m24UxM0BfwMs576YyuW0ag3RGR8

###Generate new code for coloc
PATCH http://localhost:5000/colocs/10/code
Authorization : token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJpYXQiOjE3MTMyNTUyNjgsImV4cCI6MTcxMzI1ODg2OH0.5gWQbOOIcIEM6ry1m24UxM0BfwMs576YyuW0ag3RGR8